### PR TITLE
Download only related files + autoupdate every week

### PR DESCRIPTION
**Pull request by deedy5**
1.Download only related files (do not unzip if the file is an archive),
2.Update files automatically every week,
3.Remove `Rich` and `Aiofiles`, 
4.Download files using ThreadPoolExecutor.

### CODE REVIEW

**Comment by daijro** [comment]
Thanks for the PR!

I originally used rich mainly for its support for multiple progress bars. I agree that the disk size of rich is extremely concerning for what's meant to be a lightweight modular library.

I will accept the PR, however, I think the progress bars are a nice addition for slower networks to see what's going on.
Do you think I should implement a lighter project like `tqdm`, or write a simple multi-progress bar loader that returns back the download status of the files from each thread, or is having no progress bars at all a better solution?

**Comment by deedy5** [comment]
`click.progressbar` can be used.
Example:
```python3
import click

content = "a" * 100_000

with click.progressbar(
    length=len(content),
    label='Downloading',
    show_percent=True,
    show_pos=True,
    width=50
) as bar:
    for char in content:
        bar.update(len(char))
```

I first changed from `rich` to `click.progressbar`.
But then I tested it and realized that it doesn't make sense - the files are very small and load almost instantly.

**Comment by deedy5** [comment]
I suggest another way to reduce the size -- don't unzip the files after downloading, so that they are stored on disk as archives.

**Comment by deedy5** [comment]
I added the commit so that zip-files don't unzip before saving. 
Reason:
fingerprint-network.zip = 756Kb
fingerprint-network.json = 11.8Mb

**Comment by daijro** [comment]
> But then I tested it and realized that it doesn't make sense - the files are very small and load almost instantly.

That makes sense. After thinking about it, a simple "Downloading header network definitions" or "Downloading fingerprint network definitions" could work as well.

Looks good!

**Pull request merged**
